version: "3.9"

services:
    mongo:
        image: mongo:latest
        restart: always
        env_file:
            - ../.env
        volumes:
            - "../data/mongo:/data/db"
        ports:
            - "27017:27017"

    backend:
        build:
            context: ../.
            dockerfile: deployment/Dockerfile
        restart: always
        environment:
            - DOCKER_MODE=1
        env_file:
            - ../.env
        depends_on:
            - mongo
        ports:
            - "9999:9999"

    ml:
        build:
            context: ../python/
            dockerfile: ../python/Dockerfile
        restart: always
        env_file:
            - ../.env
        ports:
            - "8000:8000"

    frontend:
        build:
            context: ../frontend/
            dockerfile: ../frontend/Dockerfile
        ports:
            - "3000:80"
